table category_opportunity

	measure 'Category scenario opportunity' = SUM(category_opportunity[scenario_extra_purchases])
		formatString: #,##0

	column product_category
		dataType: string
		summarizeBy: none
		sourceColumn: product_category

	column view_sessions
		dataType: int64
		summarizeBy: none
		sourceColumn: view_sessions

	column cart_sessions
		dataType: int64
		summarizeBy: none
		sourceColumn: cart_sessions

	column view_to_cart_rate
		dataType: double
		formatString: 0.0%
		summarizeBy: none
		sourceColumn: view_to_cart_rate

	column overall_benchmark_rate
		dataType: double
		formatString: 0.0%
		summarizeBy: none
		sourceColumn: overall_benchmark_rate

	column scenario_extra_carts
		dataType: int64
		summarizeBy: none
		sourceColumn: scenario_extra_carts

	column scenario_extra_purchases
		dataType: int64
		summarizeBy: none
		sourceColumn: scenario_extra_purchases

	partition category_opportunity = m
		mode: import
		source =
			let
				Source = Csv.Document(File.Contents(#"DataFolder" & "\category_opportunity.csv"), [Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				Typed = Table.TransformColumnTypes(Headers, {{"product_category", type text}, {"view_sessions", Int64.Type}, {"cart_sessions", Int64.Type}, {"view_to_cart_rate", type number}, {"overall_benchmark_rate", type number}, {"scenario_extra_carts", Int64.Type}, {"scenario_extra_purchases", Int64.Type}}, "en-US")
			in
				Typed
